name: Docker
on: [push,repository_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: aarnott/nbgv@v0.3
      id: nbgv
    - name: Build docker image
      run: docker build . -t containers.pkg.github.com/jcansdale/gpr:windows --build-arg READ_PACKAGES_TOKEN=${{ secrets.READ_PACKAGES_TOKEN }}
    - name: Publish to GHCR
      run: |
        docker login https://containers.pkg.github.com -u jcansdale -p ${{ secrets.GHCR_TOKEN }}
        docker push containers.pkg.github.com/jcansdale/gpr:windows
    - name: Publish to DockerHub
      run: |
        docker tag containers.pkg.github.com/jcansdale/gpr:windows jcansdale/gpr:windows
        docker login -u jcansdale -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker push jcansdale/gpr:windows
