name: Docker
on: [push,repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: aarnott/nbgv@v0.3
      id: nbgv
    - name: Build docker image
      run: docker build . -t docker.pkg.github.com/jcansdale/gpr/gpr:${{ steps.nbgv.outputs.SemVer2 }} --build-arg READ_PACKAGES_TOKEN=${{ secrets.READ_PACKAGES_TOKEN }}
    - name: Publish docker image
      run: |
        docker login -u jcansdale -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
        docker push docker.pkg.github.com/jcansdale/gpr/gpr:${{ steps.nbgv.outputs.SemVer2 }}
    - name: Publish latest from master
      if: github.ref == 'refs/heads/master'
      run: |
        docker tag docker.pkg.github.com/jcansdale/gpr/gpr:${{ steps.nbgv.outputs.SemVer2 }} docker.pkg.github.com/jcansdale/gpr/gpr
        docker push docker.pkg.github.com/jcansdale/gpr/gpr
    - name: Publish to DockerHub
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u jcansdale -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker tag docker.pkg.github.com/jcansdale/gpr/gpr:${{ steps.nbgv.outputs.SemVer2 }} jcansdale/gpr:${{ steps.nbgv.outputs.SemVer2 }}
        docker push jcansdale/gpr:${{ steps.nbgv.outputs.SemVer2 }}
        docker tag docker.pkg.github.com/jcansdale/gpr/gpr:${{ steps.nbgv.outputs.SemVer2 }} jcansdale/gpr
        docker push jcansdale/gpr
