name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Nerdbank.GitVersioning
      uses: AArnott/nbgv@v0.3
    - name: Build with dotnet
      run: dotnet pack --configuration Release
