name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install GPR tool
      run: dotnet tool install gpr --tool-path ~/tools
    - uses: actions/checkout@v1
    - name: Set API key for GitHub Package Registry
      run: ~/tools/gpr setApiKey ${{ secrets.GITHUB_TOKEN }}
    - uses: aarnott/nbgv@v0.3
      id: nbgv
    - name: Build with dotnet
      run: dotnet pack --configuration Release
    - name: Self publish tool
      run: dotnet exec ./src/GprTool/bin/Release/netcoreapp3.0/gpr.dll push ./src/GprTool/nupkg/gpr.${{ steps.nbgv.outputs.SemVer2 }}.nupkg -k ${{ secrets.GITHUB_TOKEN }}
